# Bu ödevde  NLP CLASSIFICATION & SENTIMENT ANALYSIS yapılacaktır.

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('restaurant.csv')

In [4]:
df.head()

,Unnamed: 0,review_id,user_id,business_id,stars,useful,funny,cool,text,date
0,2370338,_WTGv5XnA-qb_XD1D7Z0jg,6PgdGb3HrZdsfl2GiULo8w,RESDUcs7fIiihp38-d6_6g,5,0,1,0,After getting food poisoning at the Palms hote...,2012-12-04 03:10:18
1,2370357,JlNnsvMPLK_1-X2hwzK24w,IS9yw8P2uAPBX6FNLLX4KA,RESDUcs7fIiihp38-d6_6g,4,39,21,29,"""A feast worthy of Gods""\n\nBaccarnal Buffet i...",2014-01-17 00:50:50
2,2370373,hBkoWffORRb6aqKhC_Li2A,uZdFsE_aHbFBChgN6Xa8tw,RESDUcs7fIiihp38-d6_6g,4,1,1,1,The crab legs are better than the ones at Wick...,2015-06-08 18:03:09
3,2370411,rbkxvrgZg5kdCL2a66QYmA,8ZWJNAEWsymXDzKx3B0tTQ,RESDUcs7fIiihp38-d6_6g,1,0,0,0,Not worth it! Too salty food and expensive! Th...,2016-12-19 16:15:29
4,2370500,5tw_pedoHVi9bgeiBNsISg,E0sm4Ve7ifanFYeQMcV8Eg,RESDUcs7fIiihp38-d6_6g,5,0,0,0,I would give this infinite stars if I could. M...,2015-07-28 07:13:17

In [6]:
df['text']

0        After getting food poisoning at the Palms hote...
1        "A feast worthy of Gods"\n\nBaccarnal Buffet i...
2        The crab legs are better than the ones at Wick...
3        Not worth it! Too salty food and expensive! Th...
4        I would give this infinite stars if I could. M...
                               ...
10412    Best buffet ever! Irma was great, served us be...
10413    Hollllllyyyy moleyyyy! \n\nThis buffet was one...
10414    The selection is amazing and all the food is e...
10415    One of the best buffets I've had in Vegas. My ...
10416    I got a chance to go to the Bacchanal Buffett ...
Name: text, Length: 10417, dtype: object

In [7]:
df['text']=df['text'].str.lower() # küçük harf yapar
df['text']=df['text'].str.replace('[^\w\s]','',regex=True) # noktalama kaldır
df['text']=df['text'].str.replace('\d+','',regex=True) # rakamları kaldır
df['text']=df['text'].str.replace('\n','',regex=True) # satır sonlarını kaldır
df['text']=df['text'].str.replace('\r','',regex=True) # enterleri kaldır

In [8]:
df['text']

0        after getting food poisoning at the palms hote...
1        a feast worthy of godsbaccarnal buffet in caes...
2        the crab legs are better than the ones at wick...
3        not worth it too salty food and expensive this...
4        i would give this infinite stars if i could my...
                               ...
10412    best buffet ever irma was great served us bett...
10413    hollllllyyyy moleyyyy this buffet was one for ...
10414    the selection is amazing and all the food is e...
10415    one of the best buffets ive had in vegas my on...
10416    i got a chance to go to the bacchanal buffett ...
Name: text, Length: 10417, dtype: object

In [9]:
# Sentimel Analysis

In [10]:
ybw=df[(df.stars==1)|(df.stars==5)]

In [11]:
ybw

,Unnamed: 0,review_id,user_id,business_id,stars,useful,funny,cool,text,date
0,2370338,_WTGv5XnA-qb_XD1D7Z0jg,6PgdGb3HrZdsfl2GiULo8w,RESDUcs7fIiihp38-d6_6g,5,0,1,0,after getting food poisoning at the palms hote...,2012-12-04 03:10:18
3,2370411,rbkxvrgZg5kdCL2a66QYmA,8ZWJNAEWsymXDzKx3B0tTQ,RESDUcs7fIiihp38-d6_6g,1,0,0,0,not worth it too salty food and expensive this...,2016-12-19 16:15:29
4,2370500,5tw_pedoHVi9bgeiBNsISg,E0sm4Ve7ifanFYeQMcV8Eg,RESDUcs7fIiihp38-d6_6g,5,0,0,0,i would give this infinite stars if i could my...,2015-07-28 07:13:17
5,2370586,gmZJrnsIpYIrhPBsaAVjIw,mCHQQxluggGNYOKqpiR94g,RESDUcs7fIiihp38-d6_6g,5,0,0,0,really enjoyed everything they had to offer it...,2015-04-01 16:18:34
8,2371005,9n4EEhhLlaLDX3QQFVoHMw,or1TN9s4LSRfBF6kmzmb5g,RESDUcs7fIiihp38-d6_6g,5,0,0,0,lots of choices good service line wasnt as lon...,2017-03-27 00:42:19
...,...,...,...,...,...,...,...,...,...,...
10409,3219831,--Rcc25wmvC2YikMKO1duQ,EKLCM0XAOTq14wNnuMAGWA,RESDUcs7fIiihp38-d6_6g,5,1,0,0,we went to bacchanal on easter sunday as it wa...,2019-04-28 18:59:53
10410,3219849,LbMPx0u9mAcaVDOYiiArsQ,0wNZkuUFDnMA_8YP_PE3Zw,RESDUcs7fIiihp38-d6_6g,1,0,0,0,came him from la thanksgiving week we decided ...,2019-12-05 18:01:49
10411,3219894,ErLDRaBYPyt8x6DkJuY9TA,YhLSS4TmTFuQOrN4RAUlBw,RESDUcs7fIiihp38-d6_6g,5,0,0,0,every time we visit las vegas we go to this bu...,2019-12-05 21:34:56
10412,3220114,46xWDTFPZI9u6waHm78EKw,CT57mpNepL9q9sTYFqRbLQ,RESDUcs7fIiihp38-d6_6g,5,0,0,0,best buffet ever irma was great served us bett...,2019-11-17 20:39:36
10414,3220255,2wFmrsm8j1cyyG-DoMqKUw,kbylx63ynkXL8YBJzVfNnQ,RESDUcs7fIiihp38-d6_6g,5,0,0,0,the selection is amazing and all the food is e...,2019-12-12 03:27:22

In [12]:
ybw.reset_index(drop=True,inplace=True)

In [13]:
ybw

,Unnamed: 0,review_id,user_id,business_id,stars,useful,funny,cool,text,date
0,2370338,_WTGv5XnA-qb_XD1D7Z0jg,6PgdGb3HrZdsfl2GiULo8w,RESDUcs7fIiihp38-d6_6g,5,0,1,0,after getting food poisoning at the palms hote...,2012-12-04 03:10:18
1,2370411,rbkxvrgZg5kdCL2a66QYmA,8ZWJNAEWsymXDzKx3B0tTQ,RESDUcs7fIiihp38-d6_6g,1,0,0,0,not worth it too salty food and expensive this...,2016-12-19 16:15:29
2,2370500,5tw_pedoHVi9bgeiBNsISg,E0sm4Ve7ifanFYeQMcV8Eg,RESDUcs7fIiihp38-d6_6g,5,0,0,0,i would give this infinite stars if i could my...,2015-07-28 07:13:17
3,2370586,gmZJrnsIpYIrhPBsaAVjIw,mCHQQxluggGNYOKqpiR94g,RESDUcs7fIiihp38-d6_6g,5,0,0,0,really enjoyed everything they had to offer it...,2015-04-01 16:18:34
4,2371005,9n4EEhhLlaLDX3QQFVoHMw,or1TN9s4LSRfBF6kmzmb5g,RESDUcs7fIiihp38-d6_6g,5,0,0,0,lots of choices good service line wasnt as lon...,2017-03-27 00:42:19
...,...,...,...,...,...,...,...,...,...,...
5298,3219831,--Rcc25wmvC2YikMKO1duQ,EKLCM0XAOTq14wNnuMAGWA,RESDUcs7fIiihp38-d6_6g,5,1,0,0,we went to bacchanal on easter sunday as it wa...,2019-04-28 18:59:53
5299,3219849,LbMPx0u9mAcaVDOYiiArsQ,0wNZkuUFDnMA_8YP_PE3Zw,RESDUcs7fIiihp38-d6_6g,1,0,0,0,came him from la thanksgiving week we decided ...,2019-12-05 18:01:49
5300,3219894,ErLDRaBYPyt8x6DkJuY9TA,YhLSS4TmTFuQOrN4RAUlBw,RESDUcs7fIiihp38-d6_6g,5,0,0,0,every time we visit las vegas we go to this bu...,2019-12-05 21:34:56
5301,3220114,46xWDTFPZI9u6waHm78EKw,CT57mpNepL9q9sTYFqRbLQ,RESDUcs7fIiihp38-d6_6g,5,0,0,0,best buffet ever irma was great served us bett...,2019-11-17 20:39:36
5302,3220255,2wFmrsm8j1cyyG-DoMqKUw,kbylx63ynkXL8YBJzVfNnQ,RESDUcs7fIiihp38-d6_6g,5,0,0,0,the selection is amazing and all the food is e...,2019-12-12 03:27:22

In [14]:
x=ybw[['text']]
y=ybw[['stars']]

In [22]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from textblob import TextBlob

In [23]:
def ekkok(text):
    words = TextBlob(text).words
    return [word.lemmatize() for word in words  ]

In [24]:
vect = CountVectorizer(analyzer = ekkok, stop_words = 'english', ngram_range = (1,2))

In [25]:
xyeni = vect.fit_transform(x['text'])

C:\Users\USER\anaconda3\Lib\site-packages\sklearn\feature_extraction\text.py:533: UserWarning: The parameter 'ngram_range' will not be used since 'analyzer' is callable'
  warnings.warn(
C:\Users\USER\anaconda3\Lib\site-packages\sklearn\feature_extraction\text.py:539: UserWarning: The parameter 'stop_words' will not be used since 'analyzer' != 'word'
  warnings.warn(

In [26]:
print(vect.get_feature_names_out()[-50:])

['zinger' 'zip' 'zipped' 'ziti' 'zone' 'zonecold' 'zong' 'zoo' 'zorro'
 'zu' 'zubereitet' 'zucchini' 'zugänglich' 'zur' 'à' 'àlacarte' 'ça' 'ét'
 'étaient' 'éventail' 'évite' 'östlich' 'únicamente' 'über' 'üblich'
 'übliche' 'お料理一品一品の見た目もとても綺麗です' 'ステーキ' 'デザート達には' 'メチャ美味しいし'
 'ラスベガスに行ったらバッフェに少しお値段高めですがこちらは種類の多さ美味しさどれも良かったですわたし達が行った日は待ち時間も五分程で案内されスタッフの方々の対応も丁寧でしたどの料理も目を引くような盛り付け方や彩りがよくみているだけでもワクワクします私は野菜料理ばかり食べましたがシーフードも美味しかったと家族が言っていましたまた食べに行きたいと思えるバッフェでした'
 '中午没有雪蟹腿菜都很一般港式点心说的过去其他的中式菜只能说尚且入口寿司品质还行' '中国游客别去chinese'
 '凯撒宫的自助餐怎么可以这么棒帝王蟹生蚝虾蟹鲜美无比羊排叉烧披萨提拉米苏布丁每一样都想说umm好吃好吃' '吃出了泪花' '品揃えも豊富で'
 '大大満足' '并没有一些中式buffet好其实两小时的限制也让人不愉快前台不友好'
 '慢慢慢慢慢慢慢慢慢慢慢慢慢慢慢慢慢慢慢慢慢慢慢慢慢慢慢慢慢慢慢慢慢慢慢慢慢慢慢慢啊啊ーー' '服务很好价格也实惠' '没礼貌的服务'
 '特に茹でたカニと' '皿'
 '看了网上的广告去的非常失望菜色没有那么丰富大部分菜品颜色暗沉给人感觉不新鲜最想吃的蟹腿肉质又散又软真的没办法接受服务是没什么服务的了点完就没人理你了饮料见底也没服务人员主动添加叫个服务员还慢慢吞吞给你脸色真的太糟糕了very'
 '真心不怎么样' '肯定是请来了全球最地道的大厨吧然而才多一位甩国内的自助条街' '这里真心没有爱和很糟糕'
 '连粥和油条都做的地地道道萝卜干都是萧山的味道啊'
 '食物还可以但吃饭要排很久的队而且歧视中国人吃饭还要出示护照不是很好找在凯撒一楼赌场的里面牛排还可以但是螃蟹腿海鲜等食物一般没有想象中的好没有醋等调料吃起来可能会腻饮料需要找服务员单独要总体来说就餐体验和环境都不是很好'
 '高いけど']

In [27]:
x_train , x_test , y_train , y_test = train_test_split(xyeni , y , random_state= 42 , test_size = .20)

In [28]:
dt = DecisionTreeClassifier()

In [29]:
model = dt.fit(x_train , y_train)

In [30]:
tahmin = dt.predict(x_test)

In [31]:
accuracy_score(y_test , tahmin)

0.8765315739868049