# Laptop Price Prediction - Regression

This project aims to predict laptop prices based on various features and specifications using machine learning algorithms. The dataset contains information about different laptop models, their configurations, and corresponding prices.

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('laptop_data.csv')

In [3]:
df.head()

,Unnamed: 0,Company,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price
0,0,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,71378.6832
1,1,Apple,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,47895.5232
2,2,HP,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,1.86kg,30636.0000
3,3,Apple,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,1.83kg,135195.3360
4,4,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37kg,96095.8080

In [4]:
df.shape

(1303, 12)

## Exploratory Data Analysis - EDA

In [5]:
df.describe()

       Unnamed: 0       Inches          Price
count  1303.00000  1303.000000    1303.000000
mean    651.00000    15.017191   59870.042910
std     376.28801     1.426304   37243.201786
min       0.00000    10.100000    9270.720000
25%     325.50000    14.000000   31914.720000
50%     651.00000    15.600000   52054.560000
75%     976.50000    15.600000   79274.246400
max    1302.00000    18.400000  324954.720000

In [6]:
df.dtypes

Unnamed: 0            int64
Company              object
TypeName             object
Inches              float64
ScreenResolution     object
Cpu                  object
Ram                  object
Memory               object
Gpu                  object
OpSys                object
Weight               object
Price               float64
dtype: object

In [7]:
df.isnull().sum()

Unnamed: 0          0
Company             0
TypeName            0
Inches              0
ScreenResolution    0
Cpu                 0
Ram                 0
Memory              0
Gpu                 0
OpSys               0
Weight              0
Price               0
dtype: int64

In [8]:
df.isna().sum()

Unnamed: 0          0
Company             0
TypeName            0
Inches              0
ScreenResolution    0
Cpu                 0
Ram                 0
Memory              0
Gpu                 0
OpSys               0
Weight              0
Price               0
dtype: int64

Data is regular.

## Feature Engineering

### Screen Resolution

In [9]:
df['ScreenResolution'].value_counts()

ScreenResolution
Full HD 1920x1080                                507
1366x768                                         281
IPS Panel Full HD 1920x1080                      230
IPS Panel Full HD / Touchscreen 1920x1080         53
Full HD / Touchscreen 1920x1080                   47
1600x900                                          23
Touchscreen 1366x768                              16
Quad HD+ / Touchscreen 3200x1800                  15
IPS Panel 4K Ultra HD 3840x2160                   12
IPS Panel 4K Ultra HD / Touchscreen 3840x2160     11
4K Ultra HD / Touchscreen 3840x2160               10
IPS Panel 1366x768                                 7
Touchscreen 2560x1440                              7
4K Ultra HD 3840x2160                              7
IPS Panel Retina Display 2304x1440                 6
IPS Panel Retina Display 2560x1600                 6
Touchscreen 2256x1504                              6
IPS Panel Quad HD+ / Touchscreen 3200x1800         6
IPS Panel Touchscreen 2560x1440                    5
IPS Panel Retina Display 2880x1800                 4
1440x900                                           4
IPS Panel Touchscreen 1920x1200                    4
IPS Panel 2560x1440                                4
IPS Panel Quad HD+ 2560x1440                       3
IPS Panel Touchscreen 1366x768                     3
Quad HD+ 3200x1800                                 3
1920x1080                                          3
2560x1440                                          3
Touchscreen 2400x1600                              3
IPS Panel Quad HD+ 3200x1800                       2
IPS Panel Full HD 2160x1440                        2
IPS Panel Touchscreen / 4K Ultra HD 3840x2160      2
IPS Panel Full HD 1366x768                         1
Touchscreen / Quad HD+ 3200x1800                   1
IPS Panel Retina Display 2736x1824                 1
IPS Panel Full HD 2560x1440                        1
IPS Panel Full HD 1920x1200                        1
Touchscreen / Full HD 1920x1080                    1
Touchscreen / 4K Ultra HD 3840x2160                1
IPS Panel Touchscreen 2400x1600                    1
Name: count, dtype: int64

In [10]:
df["Resolution"] = df["ScreenResolution"].str.extract(r"(\d{3,4}x\d{3,4})", expand=False) ## ekran çözünürlüğü ayrıldı

In [11]:
df["Resolution"].value_counts()

Resolution
1920x1080    841
1366x768     308
3840x2160     43
3200x1800     27
2560x1440     23
1600x900      23
2304x1440      6
2560x1600      6
2256x1504      6
1920x1200      5
1440x900       4
2880x1800      4
2400x1600      4
2160x1440      2
2736x1824      1
Name: count, dtype: int64

In [12]:
df["Touch"] = df["ScreenResolution"].str.contains("touchscreen", case=False, na=False).astype(int) ## dokunmatik ekran ayrıldı

In [13]:
df["Touch"].value_counts()

Touch
0    1111
1     192
Name: count, dtype: int64

In [14]:
df["Panel"] = np.where(df["ScreenResolution"].str.contains(r"ips|retina", case=False, na=False), "IPS", pd.NA)

In [15]:
df["Panel"].isna().sum()

np.int64(938)

#### Screen Resolution End

### Ram

In [16]:
df['Ram'].value_counts()

Ram
8GB     619
4GB     375
16GB    200
6GB      41
12GB     25
2GB      22
32GB     17
24GB      3
64GB      1
Name: count, dtype: int64

In [17]:
df['Ram'].isnull().sum()

np.int64(0)

In [18]:
df['Ram'].isna().sum()

np.int64(0)

In [19]:
df["Ram"] = df["Ram"].str.replace("GB", "", regex=False).astype(int) # GB ifadesi silindi

In [20]:
df['Ram'].value_counts()

Ram
8     619
4     375
16    200
6      41
12     25
2      22
32     17
24      3
64      1
Name: count, dtype: int64

#### End of Ram

### Memory

In [21]:
df['Memory'].value_counts()

Memory
256GB SSD                        412
1TB HDD                          223
500GB HDD                        132
512GB SSD                        118
128GB SSD +  1TB HDD              94
128GB SSD                         76
256GB SSD +  1TB HDD              73
32GB Flash Storage                38
2TB HDD                           16
64GB Flash Storage                15
1TB SSD                           14
512GB SSD +  1TB HDD              14
256GB SSD +  2TB HDD              10
1.0TB Hybrid                       9
256GB Flash Storage                8
16GB Flash Storage                 7
32GB SSD                           6
180GB SSD                          5
128GB Flash Storage                4
16GB SSD                           3
512GB SSD +  2TB HDD               3
128GB SSD +  2TB HDD               2
256GB SSD +  256GB SSD             2
512GB Flash Storage                2
1TB SSD +  1TB HDD                 2
256GB SSD +  500GB HDD             2
64GB SSD                           1
512GB SSD +  512GB SSD             1
64GB Flash Storage +  1TB HDD      1
1TB HDD +  1TB HDD                 1
512GB SSD +  256GB SSD             1
32GB HDD                           1
128GB HDD                          1
240GB SSD                          1
8GB SSD                            1
508GB Hybrid                       1
1.0TB HDD                          1
512GB SSD +  1.0TB Hybrid          1
256GB SSD +  1.0TB Hybrid          1
Name: count, dtype: int64

In [22]:
import re

_pat = re.compile(
    r'(?P<val>\d+(?:\.\d+)?)\s*(?P<unit>TB|GB)\s*(?P<typ>SSD|HDD|Hybrid|Flash(?:\s+Storage)?)',
    re.IGNORECASE
)

def _parse_memory(s: str):
    out = {'SSD_GB': 0.0, 'HDD_GB': 0.0, 'Flash_GB': 0.0, 'Hybrid_GB': 0.0, 'Disk_Count': 0}
    if not isinstance(s, str):
        out['Total_GB'] = 0.0
        return out

    for m in _pat.finditer(s):
        val = float(m.group('val'))
        unit = m.group('unit').upper()
        typ  = m.group('typ').strip().lower()

        # Flash Storage sadeleştir
        if typ.startswith('flash'):
            typ_norm = 'Flash'
        elif typ == 'ssd':
            typ_norm = 'SSD'
        elif typ == 'hdd':
            typ_norm = 'HDD'
        else:
            typ_norm = 'Hybrid'

        gb = val * 1024.0 if unit == 'TB' else val
        out[f'{typ_norm}_GB'] += gb
        out['Disk_Count'] += 1

    out['Total_GB'] = out['SSD_GB'] + out['HDD_GB'] + out['Flash_GB'] + out['Hybrid_GB']
    return out

# Özellikleri çıkar
feats = df['Memory'].apply(_parse_memory).apply(pd.Series)

# Bayraklar ve oranlar
for t in ['SSD', 'HDD', 'Flash', 'Hybrid']:
    feats[f'Has_{t}'] = (feats[f'{t}_GB'] > 0).astype(int)
    feats[f'{t}_Ratio'] = (feats[f'{t}_GB'] / feats['Total_GB']).replace([np.inf, -np.inf], 0).fillna(0)

# İstersen kapasite sütunlarını tam sayıya yuvarla
for col in ['SSD_GB', 'HDD_GB', 'Flash_GB', 'Hybrid_GB', 'Total_GB']:
    feats[col] = feats[col].round().astype(int)

# Son DataFrame
df = pd.concat([df, feats], axis=1)

# Kontrol için ilk satırlar
print(df.head())
## ChatGpt fonksiyonu

   Unnamed: 0 Company   TypeName  Inches                    ScreenResolution  \
0           0   Apple  Ultrabook    13.3  IPS Panel Retina Display 2560x1600
1           1   Apple  Ultrabook    13.3                            1440x900
2           2      HP   Notebook    15.6                   Full HD 1920x1080
3           3   Apple  Ultrabook    15.4  IPS Panel Retina Display 2880x1800
4           4   Apple  Ultrabook    13.3  IPS Panel Retina Display 2560x1600

                          Cpu  Ram               Memory  \
0        Intel Core i5 2.3GHz    8            128GB SSD
1        Intel Core i5 1.8GHz    8  128GB Flash Storage
2  Intel Core i5 7200U 2.5GHz    8            256GB SSD
3        Intel Core i7 2.7GHz   16            512GB SSD
4        Intel Core i5 3.1GHz    8            256GB SSD

                            Gpu  OpSys  ... Disk_Count  Total_GB Has_SSD  \
0  Intel Iris Plus Graphics 640  macOS  ...        1.0       128       1
1        Intel HD Graphics 6000  macOS  ...        1.0       128       0
2         Intel HD Graphics 620  No OS  ...        1.0       256       1
3            AMD Radeon Pro 455  macOS  ...        1.0       512       1
4  Intel Iris Plus Graphics 650  macOS  ...        1.0       256       1

   SSD_Ratio Has_HDD  HDD_Ratio  Has_Flash  Flash_Ratio  Has_Hybrid  \
0        1.0       0        0.0          0          0.0           0
1        0.0       0        0.0          1          1.0           0
2        1.0       0        0.0          0          0.0           0
3        1.0       0        0.0          0          0.0           0
4        1.0       0        0.0          0          0.0           0

   Hybrid_Ratio
0           0.0
1           0.0
2           0.0
3           0.0
4           0.0

[5 rows x 29 columns]

In [23]:
df.columns

Index(['Unnamed: 0', 'Company', 'TypeName', 'Inches', 'ScreenResolution',
       'Cpu', 'Ram', 'Memory', 'Gpu', 'OpSys', 'Weight', 'Price', 'Resolution',
       'Touch', 'Panel', 'SSD_GB', 'HDD_GB', 'Flash_GB', 'Hybrid_GB',
       'Disk_Count', 'Total_GB', 'Has_SSD', 'SSD_Ratio', 'Has_HDD',
       'HDD_Ratio', 'Has_Flash', 'Flash_Ratio', 'Has_Hybrid', 'Hybrid_Ratio'],
      dtype='object')

In [24]:
df[ ['SSD_GB', 'HDD_GB', 'Flash_GB', 'Hybrid_GB',
       'Disk_Count', 'Total_GB', 'Has_SSD', 'SSD_Ratio', 'Has_HDD',
       'HDD_Ratio', 'Has_Flash', 'Flash_Ratio', 'Has_Hybrid', 'Hybrid_Ratio']]

,SSD_GB,HDD_GB,Flash_GB,Hybrid_GB,Disk_Count,Total_GB,Has_SSD,SSD_Ratio,Has_HDD,HDD_Ratio,Has_Flash,Flash_Ratio,Has_Hybrid,Hybrid_Ratio
0,128,0,0,0,1.0,128,1,1.0,0,0.0,0,0.0,0,0.0
1,0,0,128,0,1.0,128,0,0.0,0,0.0,1,1.0,0,0.0
2,256,0,0,0,1.0,256,1,1.0,0,0.0,0,0.0,0,0.0
3,512,0,0,0,1.0,512,1,1.0,0,0.0,0,0.0,0,0.0
4,256,0,0,0,1.0,256,1,1.0,0,0.0,0,0.0,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1298,128,0,0,0,1.0,128,1,1.0,0,0.0,0,0.0,0,0.0
1299,512,0,0,0,1.0,512,1,1.0,0,0.0,0,0.0,0,0.0
1300,0,0,64,0,1.0,64,0,0.0,0,0.0,1,1.0,0,0.0
1301,0,1024,0,0,1.0,1024,0,0.0,1,1.0,0,0.0,0,0.0
1302,0,500,0,0,1.0,500,0,0.0,1,1.0,0,0.0,0,0.0

#### End of Memory

### Weight

In [25]:
df['Weight'].value_counts()

Weight
2.2kg      121
2.1kg       58
2.4kg       44
2.3kg       41
2.5kg       38
          ...
3.52kg       1
2.21kg       1
2.191kg      1
2.34kg       1
4.0kg        1
Name: count, Length: 179, dtype: int64

In [26]:
df['Weight'].head(10)

0    1.37kg
1    1.34kg
2    1.86kg
3    1.83kg
4    1.37kg
5     2.1kg
6    2.04kg
7    1.34kg
8     1.3kg
9     1.6kg
Name: Weight, dtype: object

In [27]:
df["Weight"] = df["Weight"].str.replace("kg", "", regex=False).astype(float)

In [28]:
df['Weight'].value_counts()

Weight
2.200    126
2.100     58
2.000     45
2.400     44
2.300     41
        ...
0.990      1
2.591      1
2.210      1
2.191      1
2.340      1
Name: count, Length: 171, dtype: int64

In [29]:
df['Weight'].head(10)

0    1.37
1    1.34
2    1.86
3    1.83
4    1.37
5    2.10
6    2.04
7    1.34
8    1.30
9    1.60
Name: Weight, dtype: float64

#### End of weight

### OpSys

In [30]:
df['OpSys'].value_counts()

OpSys
Windows 10      1072
No OS             66
Linux             62
Windows 7         45
Chrome OS         27
macOS             13
Mac OS X           8
Windows 10 S       8
Android            2
Name: count, dtype: int64

 Fiyata etki edeceğini düşünüyorum ama çoğunluk windows olduğu için get dummies yapıcam , doğruluk oranım düşük çıkarsa arttırmak için 
bu sütunu kullanabilirim.

In [31]:
pd.get_dummies(df['OpSys'])

,Android,Chrome OS,Linux,Mac OS X,No OS,Windows 10,Windows 10 S,Windows 7,macOS
0,False,False,False,False,False,False,False,False,True
1,False,False,False,False,False,False,False,False,True
2,False,False,False,False,True,False,False,False,False
3,False,False,False,False,False,False,False,False,True
4,False,False,False,False,False,False,False,False,True
...,...,...,...,...,...,...,...,...,...
1298,False,False,False,False,False,True,False,False,False
1299,False,False,False,False,False,True,False,False,False
1300,False,False,False,False,False,True,False,False,False
1301,False,False,False,False,False,True,False,False,False
1302,False,False,False,False,False,True,False,False,False

#### End of OpSys

### CPU

In [32]:
df['Cpu'].value_counts()

Cpu
Intel Core i5 7200U 2.5GHz       190
Intel Core i7 7700HQ 2.8GHz      146
Intel Core i7 7500U 2.7GHz       134
Intel Core i7 8550U 1.8GHz        73
Intel Core i5 8250U 1.6GHz        72
                                ...
Intel Core i5 7200U 2.70GHz        1
Intel Core M M7-6Y75 1.2GHz        1
Intel Core M 6Y54 1.1GHz           1
AMD E-Series 9000 2.2GHz           1
Samsung Cortex A72&A53 2.0GHz      1
Name: count, Length: 118, dtype: int64

In [33]:
def parse_cpu(cpu_str):
    parts = {}
    
    # Marka
    if "Intel" in cpu_str:
        parts["CpuBrand"] = "Intel"
    elif "AMD" in cpu_str:
        parts["CpuBrand"] = "AMD"
    else:
        parts["CpuBrand"] = "Other"
    
    # Aile (Core i3/i5/i7/i9, Ryzen, Pentium, Celeron, Atom, Xeon)
    match_family = re.search(r"(Core i[3579]|Ryzen \d|Pentium|Celeron|Atom|Xeon)", cpu_str)
    parts["CpuFamily"] = match_family.group(0) if match_family else "Other"
    
    # Model kodu (örn: 7200U, 8550U, 9420)
    match_model = re.search(r"\d{4,}[A-Z]?", cpu_str)
    parts["CpuModel"] = match_model.group(0) if match_model else "Unknown"
    
    # Saat hızı (GHz → float)
    match_speed = re.search(r"(\d\.\d+)GHz", cpu_str)
    parts["CpuSpeedGHz"] = float(match_speed.group(1)) if match_speed else None
    
    return pd.Series(parts)

In [34]:
cpu_features = df["Cpu"].apply(parse_cpu)

In [35]:
# Orijinal tabloya ekle
df = pd.concat([df, cpu_features], axis=1)

In [36]:
df.head()

,Unnamed: 0,Company,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,...,Has_HDD,HDD_Ratio,Has_Flash,Flash_Ratio,Has_Hybrid,Hybrid_Ratio,CpuBrand,CpuFamily,CpuModel,CpuSpeedGHz
0,0,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8,128GB SSD,Intel Iris Plus Graphics 640,macOS,...,0,0.0,0,0.0,0,0.0,Intel,Core i5,Unknown,2.3
1,1,Apple,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8,128GB Flash Storage,Intel HD Graphics 6000,macOS,...,0,0.0,1,1.0,0,0.0,Intel,Core i5,Unknown,1.8
2,2,HP,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8,256GB SSD,Intel HD Graphics 620,No OS,...,0,0.0,0,0.0,0,0.0,Intel,Core i5,7200U,2.5
3,3,Apple,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16,512GB SSD,AMD Radeon Pro 455,macOS,...,0,0.0,0,0.0,0,0.0,Intel,Core i7,Unknown,2.7
4,4,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8,256GB SSD,Intel Iris Plus Graphics 650,macOS,...,0,0.0,0,0.0,0,0.0,Intel,Core i5,Unknown,3.1

#### End Of CPU

### GPU

In [46]:
def parse_gpu(gpu_str: str):
    s = str(gpu_str)
    parts = {}

    # --- Marka (Brand) ---
    if re.search(r"\b(nvidia|geforce|quadro)\b", s, re.I):
        parts["GpuBrand"] = "Nvidia"
    elif re.search(r"\b(amd|radeon)\b", s, re.I):
        parts["GpuBrand"] = "AMD"
    elif re.search(r"\bintel\b", s, re.I):
        parts["GpuBrand"] = "Intel"
    elif re.search(r"\b(apple|m1|m2|m3)\b", s, re.I):
        parts["GpuBrand"] = "Apple"
    elif re.search(r"\b(arm|mali|adreno|powerVR)\b", s, re.I):
        parts["GpuBrand"] = "ARM"
    else:
        parts["GpuBrand"] = "Other"

    # --- Aile / Sınıf (Family/Class) ---
    family = "Other"
    family_patterns = [
        (r"\brtx\b", "RTX"),
        (r"\bgtx\b", "GTX"),
        (r"\bquadro\b", "Quadro"),
        (r"\bgeforce\b", "GeForce"),
        (r"\bradeon\s*rx\b", "Radeon RX"),
        (r"\bradeon\s*pro\b", "Radeon Pro"),
        (r"\bvega\b", "Vega"),
        (r"\bradeon\b", "Radeon"),
        (r"\biris\s*plus\b", "Iris Plus"),
        (r"\biris\b", "Iris"),
        (r"\buhd\b", "UHD Graphics"),
        (r"\bhd\s*graphics\b", "HD Graphics"),
        (r"\barc\b", "Intel Arc"),
    ]
    for pat, lab in family_patterns:
        if re.search(pat, s, re.I):
            family = lab
            break
    parts["GpuFamily"] = family

    # --- Model (sayısal/sonek) ---
    model = None
    model_patterns = [
        r"RTX\s*(\d{3,4}\s*(?:Ti|SUPER)?)",
        r"GTX\s*(\d{3,4}\s*(?:Ti|M|MX)?)",
        r"Quadro\s*([A-Z]?\d{3,4})",
        r"GeForce\s*(?:[A-Z]*\s*)?(\d{3,4}\s*(?:Ti|MX)?)",
        r"Radeon\s*RX\s*(\d{3,4}\s*(?:XT)?)",
        r"Radeon\s*Pro\s*(\d{3,4})",
        r"Radeon\s*(HD\s*\d{4})",
        r"Vega\s*(\d{1,2})",
        r"Iris\s*Plus\s*Graphics\s*(\d{3,4})",
        r"UHD\s*Graphics\s*(\d{3})",
        r"HD\s*Graphics\s*(\d{3,4})",
        r"Arc\s*(A\d{3})",
    ]
    for mp in model_patterns:
        m = re.search(mp, s, re.I)
        if m:
            model = m.group(1).strip()
            break
    if not model:
        m_fallback = re.search(r"\b(\d{3,4})(?:[A-Z]{0,2})\b", s)
        if m_fallback:
            model = m_fallback.group(1)
    parts["GpuModel"] = model if model else "Unknown"

    # --- Entegre mi? (Integrated) ---
    s_low = s.lower()
    integrated = False
    if parts["GpuBrand"] == "Intel":
        integrated = True
    elif "integrated" in s_low:
        integrated = True
    elif parts["GpuBrand"] == "AMD":
        if re.search(r"radeon\s*(rx|pro|vega)", s_low):
            integrated = False
        elif re.search(r"radeon\s*(r\d|graphics)", s_low):
            integrated = True
        else:
            integrated = False
    elif parts["GpuBrand"] == "Nvidia":
        integrated = False
    else:
        integrated = False

    parts["GpuIntegrated"] = integrated
    return pd.Series(parts)

# Yeni GPU sütunlarını üret ve birleştir
gpu_features = df["Gpu"].apply(parse_gpu)
df = pd.concat([df, gpu_features], axis=1)

# Kontrol için ilk 20 satır
print(df[["Gpu", "GpuBrand", "GpuFamily", "GpuModel", "GpuIntegrated"]].head(20))

                             Gpu GpuBrand     GpuFamily GpuModel  \
0   Intel Iris Plus Graphics 640    Intel     Iris Plus      640
1         Intel HD Graphics 6000    Intel   HD Graphics     6000
2          Intel HD Graphics 620    Intel   HD Graphics      620
3             AMD Radeon Pro 455      AMD    Radeon Pro      455
4   Intel Iris Plus Graphics 650    Intel     Iris Plus      650
5                  AMD Radeon R5      AMD        Radeon  Unknown
6        Intel Iris Pro Graphics    Intel          Iris  Unknown
7         Intel HD Graphics 6000    Intel   HD Graphics     6000
8           Nvidia GeForce MX150   Nvidia       GeForce      150
9         Intel UHD Graphics 620    Intel  UHD Graphics      620
10         Intel HD Graphics 620    Intel   HD Graphics      620
11         Intel HD Graphics 520    Intel   HD Graphics      520
12            AMD Radeon Pro 555      AMD    Radeon Pro      555
13            AMD Radeon R5 M430      AMD        Radeon  Unknown
14         Intel HD Graphics 615    Intel   HD Graphics      615
15  Intel Iris Plus Graphics 640    Intel     Iris Plus      640
16            AMD Radeon R5 M430      AMD        Radeon  Unknown
17            AMD Radeon Pro 560      AMD    Radeon Pro      560
18          Nvidia GeForce 940MX   Nvidia       GeForce    940MX
19        Intel UHD Graphics 620    Intel  UHD Graphics      620

    GpuIntegrated
0            True
1            True
2            True
3           False
4            True
5            True
6            True
7            True
8           False
9            True
10           True
11           True
12          False
13           True
14           True
15           True
16           True
17          False
18          False
19           True

In [47]:
df.columns

Index(['Unnamed: 0', 'Company', 'TypeName', 'Inches', 'ScreenResolution',
       'Cpu', 'Ram', 'Memory', 'Gpu', 'OpSys', 'Weight', 'Price', 'Resolution',
       'Touch', 'Panel', 'SSD_GB', 'HDD_GB', 'Flash_GB', 'Hybrid_GB',
       'Disk_Count', 'Total_GB', 'Has_SSD', 'SSD_Ratio', 'Has_HDD',
       'HDD_Ratio', 'Has_Flash', 'Flash_Ratio', 'Has_Hybrid', 'Hybrid_Ratio',
       'CpuBrand', 'CpuFamily', 'CpuModel', 'CpuSpeedGHz', 'GpuBrand',
       'GpuFamily', 'GpuModel', 'GpuIntegrated'],
      dtype='object')

In [48]:
df.head()

,Unnamed: 0,Company,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,...,Has_Hybrid,Hybrid_Ratio,CpuBrand,CpuFamily,CpuModel,CpuSpeedGHz,GpuBrand,GpuFamily,GpuModel,GpuIntegrated
0,0,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8,128GB SSD,Intel Iris Plus Graphics 640,macOS,...,0,0.0,Intel,Core i5,Unknown,2.3,Intel,Iris Plus,640,True
1,1,Apple,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8,128GB Flash Storage,Intel HD Graphics 6000,macOS,...,0,0.0,Intel,Core i5,Unknown,1.8,Intel,HD Graphics,6000,True
2,2,HP,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8,256GB SSD,Intel HD Graphics 620,No OS,...,0,0.0,Intel,Core i5,7200U,2.5,Intel,HD Graphics,620,True
3,3,Apple,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16,512GB SSD,AMD Radeon Pro 455,macOS,...,0,0.0,Intel,Core i7,Unknown,2.7,AMD,Radeon Pro,455,False
4,4,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8,256GB SSD,Intel Iris Plus Graphics 650,macOS,...,0,0.0,Intel,Core i5,Unknown,3.1,Intel,Iris Plus,650,True

In [49]:
df.to_excel("laptop_data_ready.xlsx", index=False)

#### End of GPU

### General Regulation

In [50]:
df = df.drop(['Unnamed: 0', 'Cpu', 'Memory', 'Gpu', 'ScreenResolution',
              'CpuModel', 'GpuModel', 'Panel'], axis=1)

In [ ]:
'''
        "Unnamed: 0",      # index sütunu
        "Cpu",             # ham CPU bilgisi
        "Memory",          # ham bellek bilgisi
        "Gpu",             # ham GPU bilgisi
        "ScreenResolution",# ham ekran çözünürlüğü
        "CpuModel",        # çok yüksek kardinalite
        "GpuModel",        # çok yüksek kardinalite
        "Panel"            # çok eksik veri
'''