In [1]:
# Regression

In [2]:
alis = [1,2,4,5,6,7,8,9,10]
satis = [2,4,6,8,10,12,14,16,18,20]

In [3]:
 # y = 2* x bağlantısı var

In [4]:
alis = [1,2,4,5,6,7,8,9,10]
satis = [5,7,9,11,13,15,17,19,21,23]
# y = 2*x+3 bağlantısı var

In [5]:
#####

In [6]:
x = [1,2,3,4,5,6,7,8,9,10]
y = [2,4,6,8,10,12,14,16,18,20]

In [7]:
from sklearn.linear_model import LinearRegression

In [8]:
lr = LinearRegression()

In [9]:
import pandas as pd
import numpy as np

In [10]:
# Eğitilecek verinin sütun olması gerekli

In [11]:
x = np.array(x).reshape(-1,1)

In [12]:
x

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])

In [13]:
lr.fit(x,y)

LinearRegression()

In [14]:
lr.coef_

array([2.])

In [15]:
## Model 2 ile çarpacapını anlamış

In [16]:
lr.predict([[60]])

array([120.])

In [17]:
## Model e 60 verilince 120 olacağını tahmin etti

In [18]:
lr.predict([[7.5]])

array([15.])

In [19]:
#################################

In [24]:
x = [1,2,3,4,5,6,7,8,9,10]
y = [5,7,9,11,13,15,17,19,21,23]
# y = 2*x+3 bağlantısı var

In [25]:
x = pd.array(x).reshape(-1,1)

In [26]:
x

<IntegerArray>
[
[1],
[2],
[3],
[4],
[5],
[6],
[7],
[8],
[9],
[10]
]
Shape: (10, 1), dtype: Int64

In [27]:
lr.fit(x,y)

LinearRegression()

In [28]:
lr.coef_

array([2.])

In [29]:
lr.predict([[7.5]])

array([18.])

In [31]:
lr.predict([[60]])

array([123.])

In [32]:
# Classification

In [37]:
data = {
    'Age': [25, 30, 35, 40, None],
    'Gender': ['Male', 'Female', 'Male', 'Female', 'Male'],
    'Salary': [50000, 60000, 70000, None, 90000]
}

In [39]:
df = pd.DataFrame(data)

In [40]:
df

    Age  Gender   Salary
0  25.0    Male  50000.0
1  30.0  Female  60000.0
2  35.0    Male  70000.0
3  40.0  Female      NaN
4   NaN    Male  90000.0

In [41]:
df['Age'] = df['Age'].fillna(df.Age.mean())

In [42]:
df['Salary'] = df['Salary'].fillna(df.Salary.mean())

In [43]:
df

    Age  Gender   Salary
0  25.0    Male  50000.0
1  30.0  Female  60000.0
2  35.0    Male  70000.0
3  40.0  Female  67500.0
4  32.5    Male  90000.0

In [48]:
x = df[['Age','Gender']]
y = df[['Salary']]

In [50]:
x = pd.get_dummies(x , drop_first = True)

In [51]:
x

    Age  Gender_Male
0  25.0         True
1  30.0        False
2  35.0         True
3  40.0        False
4  32.5         True

In [53]:
from sklearn.preprocessing import StandardScaler

In [55]:
sc = StandardScaler()

In [56]:
x = sc.fit_transform(x)

In [58]:
from sklearn.model_selection import train_test_split

In [60]:
x_train,x_test,y_train,y_test  = train_test_split(x,y,random_state = 42 , test_size = .2)

In [67]:
from sklearn.tree import DecisionTreeRegressor

In [68]:
dt = DecisionTreeRegressor()

In [69]:
model = dt.fit(x_train, y_train)

In [70]:
tahmin = model.predict(x_test)

In [72]:
from sklearn.metrics import r2_score

In [73]:
r2_score(tahmin , y_test)

C:\Users\USER\anaconda3\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)

nan

In [74]:
# classification yapalım derken regression yaptık

In [75]:
yeni_data = [[25,True]]

In [79]:
yd = sc.fit_transform(yeni_data) #tahmin datasını normalize edip verdik

In [80]:
model.predict(yd)

array([90000.])