In [3]:
# Film tavsiyesi - K en yakın komşu

In [4]:
import pandas as pd

In [5]:
rating = pd.read_csv('ml-100k/ml-100k/u.data' , sep = '\t', header = None , names = ['user_id', 'movie_id' , 'rating'] , usecols=range(3))
# veriler virgülle ayrılmadığı için sep ile ayırma ifadesini seçtik , başlıkta eklemedikleri için header none seçtik , sütun isimlerini verdik, kolonları ayarladık usecol ile

In [6]:
rating.head()

   user_id  movie_id  rating
0      196       242       3
1      186       302       3
2       22       377       1
3      244        51       2
4      166       346       1

In [9]:
movies = pd.read_csv('ml-100k/ml-100k/u.item' , encoding =' iso-8859-1', sep = '|' , header = None )

In [10]:
movies.head()

,0,1,2,3,4,5,6,7,8,9,...,14,15,16,17,18,19,20,21,22,23
0,1,Toy Story (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Toy%20Story%2...,0,0,0,1,1,...,0,0,0,0,0,0,0,0,0,0
1,2,GoldenEye (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?GoldenEye%20(...,0,1,1,0,0,...,0,0,0,0,0,0,0,1,0,0
2,3,Four Rooms (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Four%20Rooms%...,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
3,4,Get Shorty (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Get%20Shorty%...,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,5,Copycat (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Copycat%20(1995),0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0

In [7]:
user = pd.read_csv('ml-100k/ml-100k/u.user' , sep = '|' , header = None , names = ['name_id' , 'Age' , 'Gender' ,'Profession ', 'Zipcode' ])

In [8]:
user

     name_id  Age Gender    Profession  Zipcode
0          1   24      M     technician   85711
1          2   53      F          other   94043
2          3   23      M         writer   32067
3          4   24      M     technician   43537
4          5   33      F          other   15213
..       ...  ...    ...            ...     ...
938      939   26      F        student   33319
939      940   32      M  administrator   02215
940      941   20      M        student   97229
941      942   48      F      librarian   78209
942      943   22      M        student   77841

[943 rows x 5 columns]

In [9]:
# tabloları birleştircez

In [10]:
rating = pd.merge(movies , rating)

In [11]:
rating.head()

   movie_id             title  user_id  rating
0         1  Toy Story (1995)      308       4
1         1  Toy Story (1995)      287       5
2         1  Toy Story (1995)      148       4
3         1  Toy Story (1995)      280       4
4         1  Toy Story (1995)       66       3

In [12]:
rating.title.value_counts()

title
Star Wars (1977)                        583
Contact (1997)                          509
Fargo (1996)                            508
Return of the Jedi (1983)               507
Liar Liar (1997)                        485
                                       ...
Invitation, The (Zaproszenie) (1986)      1
Symphonie pastorale, La (1946)            1
Nothing Personal (1995)                   1
Ripe (1996)                               1
Brother's Kiss, A (1997)                  1
Name: count, Length: 1664, dtype: int64

In [13]:
mr = rating.pivot_table(index = ['user_id'] , columns=['title'], values = 'rating')

In [14]:
mr.head()

title,'Til There Was You (1997),1-900 (1994),101 Dalmatians (1996),12 Angry Men (1957),187 (1997),2 Days in the Valley (1996),"20,000 Leagues Under the Sea (1954)",2001: A Space Odyssey (1968),3 Ninjas: High Noon At Mega Mountain (1998),"39 Steps, The (1935)",...,Yankee Zulu (1994),Year of the Horse (1997),You So Crazy (1994),Young Frankenstein (1974),Young Guns (1988),Young Guns II (1990),"Young Poisoner's Handbook, The (1995)",Zeus and Roxanne (1997),unknown,Á köldum klaka (Cold Fever) (1994)
user_id,,,,,,,,,,,,,,,,,,,,,
1,NaN,NaN,2.0,5.0,NaN,NaN,3.0,4.0,NaN,NaN,...,NaN,NaN,NaN,5.0,3.0,NaN,NaN,NaN,4.0,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,2.0,NaN,NaN,NaN,NaN,4.0,NaN,NaN,...,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN,4.0,NaN

In [17]:
mr['Star Wars (1977)']

user_id
1      5.0
2      5.0
3      NaN
4      5.0
5      4.0
      ...
939    NaN
940    4.0
941    NaN
942    5.0
943    4.0
Name: Star Wars (1977), Length: 943, dtype: float64

In [18]:
# Star Wars Rating swr
swr =mr['Star Wars (1977)']

In [19]:
swr.value_counts()

Star Wars (1977)
5.0    325
4.0    176
3.0     57
2.0     16
1.0      9
Name: count, dtype: int64

In [22]:
mr[['Star Wars (1977)', '101 Dalmatians (1996)' ]].corr()

title                  Star Wars (1977)  101 Dalmatians (1996)
title
Star Wars (1977)               1.000000               0.211132
101 Dalmatians (1996)          0.211132               1.000000

In [24]:
rating.movie_id.nunique()

1682

In [28]:
sm = mr.corrwith(swr)

C:\Users\USER\anaconda3\Lib\site-packages\numpy\lib\_function_base_impl.py:2999: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
C:\Users\USER\anaconda3\Lib\site-packages\numpy\lib\_function_base_impl.py:3000: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
C:\Users\USER\anaconda3\Lib\site-packages\numpy\lib\_function_base_impl.py:2991: RuntimeWarning: Degrees of freedom <= 0 for slice
  c = cov(x, y, rowvar, dtype=dtype)
C:\Users\USER\anaconda3\Lib\site-packages\numpy\lib\_function_base_impl.py:2848: RuntimeWarning: divide by zero encountered in divide
  c *= np.true_divide(1, fact)
C:\Users\USER\anaconda3\Lib\site-packages\numpy\lib\_function_base_impl.py:2848: RuntimeWarning: invalid value encountered in multiply
  c *= np.true_divide(1, fact)

In [30]:
sm.sort_values(ascending = False)

title
Hollow Reed (1996)                         1.0
Stripes (1981)                             1.0
Man of the Year (1995)                     1.0
Good Man in Africa, A (1994)               1.0
Twisted (1996)                             1.0
                                          ...
Wonderland (1997)                          NaN
Wooden Man's Bride, The (Wu Kui) (1994)    NaN
Yankee Zulu (1994)                         NaN
You So Crazy (1994)                        NaN
Á köldum klaka (Cold Fever) (1994)         NaN
Length: 1664, dtype: float64

In [32]:
import numpy as np

In [33]:
mstats = rating.groupby('title').agg({'rating': [np.size , np.mean] })

C:\Users\USER\AppData\Local\Temp\ipykernel_18872\482550376.py:1: FutureWarning: The provided callable <function mean at 0x000001EC607B72E0> is currently using SeriesGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  mstats = rating.groupby('title').agg({'rating': [np.size , np.mean] })

In [34]:
mstats.head()

                          rating
                            size      mean
title
'Til There Was You (1997)      9  2.333333
1-900 (1994)                   5  2.600000
101 Dalmatians (1996)        109  2.908257
12 Angry Men (1957)          125  4.344000
187 (1997)                    41  3.024390

In [38]:
pm = mstats[mstats['rating']['size']>100]

In [39]:
pm.sort_values(('rating', 'mean'), ascending = False)

                                 rating
                                   size      mean
title
Close Shave, A (1995)               112  4.491071
Schindler's List (1993)             298  4.466443
Wrong Trousers, The (1993)          118  4.466102
Casablanca (1942)                   243  4.456790
Shawshank Redemption, The (1994)    283  4.445230
...                                 ...       ...
Spawn (1997)                        143  2.615385
Event Horizon (1997)                127  2.574803
Crash (1996)                        128  2.546875
Jungle2Jungle (1997)                132  2.439394
Cable Guy, The (1996)               106  2.339623

[334 rows x 2 columns]

In [40]:
smdata = pd.DataFrame(sm , columns = ['similarity'])

In [42]:
pm.columns = pm.columns.get_level_values(0)
df = pm.join(smdata)

In [44]:
df.sort_values(['similarity'] , ascending = False)

,rating,rating,similarity
title,,,
Star Wars (1977),583,4.358491,1.000000
"Empire Strikes Back, The (1980)",367,4.204360,0.747981
Return of the Jedi (1983),507,4.007890,0.672556
Raiders of the Lost Ark (1981),420,4.252381,0.536117
Austin Powers: International Man of Mystery (1997),130,3.246154,0.377433
...,...,...,...
"Edge, The (1997)",113,3.539823,-0.127167
As Good As It Gets (1997),112,4.196429,-0.130466
Crash (1996),128,2.546875,-0.148507
G.I. Jane (1997),175,3.360000,-0.176734
"First Wives Club, The (1996)",160,3.018750,-0.194496