##World military power Projesini Kümeleme kullanarak çözeceğiz

In [1]:
import pandas as pd
pd.set_option("display.max_columns",100)

import warnings
warnings.filterwarnings('ignore')

import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
### Sütun isimleri birinci satırdan itibaren başlıyor . o yüzden sütun isimlerini birinci satırdan itibaren almalıyız

In [3]:
df_raw = pd.read_excel('World military power.xlsx')

In [4]:
df = df_raw[2:].copy()
df.columns = df_raw.iloc[0]
df.reset_index(drop=True, inplace=True)

## Begin EXPLORATORY DATA ANALYSIS (EDA)

In [5]:
df.head()

,Military Strength,Military Strength Power Index,Aircraft Strength,Aircraft Strength value,Fighter/Interceptor Strength,Fighter/Interceptor Strength value,Attack Aircraft Strength,Attack Aircraft Strength value,Transport Aircraft Fleet Strength,Transport Aircraft Fleet Strength value,Trainer Aircraft Fleet,Trainer Aircraft Fleet value,Helicopter Fleet Strength,Helicopter Fleet Strength value,Attack Helicopter Fleet Strength,Attack Helicopter Fleet Strength value,Tank Strength,Tank Strength value,AFV/APC Strength,AFV/APC Strength value,Self-Propelled Artillery Strength,Self-Propelled Artillery Strength value,Towed Artillery Strength,Towed Artillery Strength value,Rocket Projector Strength,Rocket Projector Strength value,Navy Fleet Strengths,Navy Fleet Strengths value,Aircraft Carrier Fleet Strength,Aircraft Carrier Fleet Strength value,Submarine Fleet Strength,Submarine Fleet Strength value,Destroyer Fleet Strength,Destroyer Fleet Strength value,Frigate Fleet Strength,Frigate Fleet Strength value,defense spending budget,defense spending budget value,External Debt,External Debt value,Airport Totals,Airport Totals value,Oil Production,Oil Production value,Oil Consumption,Oil Consumption value,Proven Oil Reserves,Proven Oil Reserves value,Available Manpower,Available Manpower value,Total Population,Total Population value,Total Square Land Area,Total Square Land Area value,Total Coastline Coverage,Total Coastline Coverage value,Total Waterway Coverage,Total Waterway Coverage value,Total Border Coverage,Total Border Coverage value
0,Albania,2.3137,Albania,19,Albania,0,Albania,0,Albania,0,Albania,0,Albania,19,Albania,0,Albania,0,Albania,467,Albania,0,Albania,0,Albania,0,Albania,38,Albania,0,Albania,0,Albania,0,Albania,0,Albania,"25,00,00,000",Albania,"9,50,50,00,000",Albania,4,Albania,16000,Albania,42500,Albania,"16,83,00,000",Albania,"15,19,438",Albania,"30,57,220",Albania,28748,Albania,362,Albania,41,Albania,691
1,Algeria,0.4659,Algeria,551,Algeria,103,Algeria,22,Algeria,59,Algeria,87,Algeria,257,Algeria,45,Algeria,880,Algeria,7361,Algeria,320,Algeria,240,Algeria,316,Algeria,201,Algeria,0,Algeria,6,Algeria,0,Algeria,5,Algeria,"13,00,00,00,000",Algeria,"6,26,00,00,000",Algeria,157,Algeria,"13,06,000",Algeria,"3,25,000",Algeria,"12,20,00,00,000",Algeria,"2,07,41,263",Algeria,"4,16,57,488",Algeria,"23,81,741",Algeria,998,Algeria,0,Algeria,6734
2,Angola,0.8379,Angola,295,Angola,72,Angola,18,Angola,30,Angola,47,Angola,126,Angola,15,Angola,379,Angola,595,Angola,28,Angola,357,Angola,115,Angola,57,Angola,0,Angola,0,Angola,0,Angola,0,Angola,"7,00,00,00,000",Angola,"42,08,00,00,000",Angola,176,Angola,"16,66,000",Angola,82300,Angola,"8,27,30,00,000",Angola,"62,44,205",Angola,"3,03,55,880",Angola,"12,46,700",Angola,1600,Angola,1300,Angola,5369
3,Argentina,0.6521,Argentina,227,Argentina,24,Argentina,7,Argentina,9,Argentina,64,Argentina,100,Argentina,0,Argentina,370,Argentina,739,Argentina,83,Argentina,172,Argentina,26,Argentina,49,Argentina,0,Argentina,2,Argentina,4,Argentina,0,Argentina,"4,20,00,00,000",Argentina,"2,14,90,00,00,000",Argentina,1138,Argentina,"4,79,400",Argentina,"6,85,000",Argentina,"2,18,50,00,000",Argentina,"2,01,79,430",Argentina,"4,46,94,198",Argentina,"27,80,400",Argentina,4989,Argentina,11000,Argentina,11968
4,Armenia,2.1251,Armenia,64,Armenia,0,Armenia,9,Armenia,3,Armenia,13,Armenia,37,Armenia,20,Armenia,110,Armenia,748,Armenia,38,Armenia,150,Armenia,68,Armenia,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Armenia,"1,38,50,00,000",Armenia,"10,41,00,00,000",Armenia,11,Armenia,0,Armenia,47500,Armenia,0,Armenia,"16,96,085",Armenia,"30,38,217",Armenia,29743,NaN,NaN,Armenia,0,Armenia,1570

In [6]:
df.tail()

,Military Strength,Military Strength Power Index,Aircraft Strength,Aircraft Strength value,Fighter/Interceptor Strength,Fighter/Interceptor Strength value,Attack Aircraft Strength,Attack Aircraft Strength value,Transport Aircraft Fleet Strength,Transport Aircraft Fleet Strength value,Trainer Aircraft Fleet,Trainer Aircraft Fleet value,Helicopter Fleet Strength,Helicopter Fleet Strength value,Attack Helicopter Fleet Strength,Attack Helicopter Fleet Strength value,Tank Strength,Tank Strength value,AFV/APC Strength,AFV/APC Strength value,Self-Propelled Artillery Strength,Self-Propelled Artillery Strength value,Towed Artillery Strength,Towed Artillery Strength value,Rocket Projector Strength,Rocket Projector Strength value,Navy Fleet Strengths,Navy Fleet Strengths value,Aircraft Carrier Fleet Strength,Aircraft Carrier Fleet Strength value,Submarine Fleet Strength,Submarine Fleet Strength value,Destroyer Fleet Strength,Destroyer Fleet Strength value,Frigate Fleet Strength,Frigate Fleet Strength value,defense spending budget,defense spending budget value,External Debt,External Debt value,Airport Totals,Airport Totals value,Oil Production,Oil Production value,Oil Consumption,Oil Consumption value,Proven Oil Reserves,Proven Oil Reserves value,Available Manpower,Available Manpower value,Total Population,Total Population value,Total Square Land Area,Total Square Land Area value,Total Coastline Coverage,Total Coastline Coverage value,Total Waterway Coverage,Total Waterway Coverage value,Total Border Coverage,Total Border Coverage value
132,Venezuela,0.6449,Venezuela,260,Venezuela,38,Venezuela,0,Venezuela,52,Venezuela,82,Venezuela,86,Venezuela,10,Venezuela,390,Venezuela,600,Venezuela,73,Venezuela,104,Venezuela,36,Venezuela,49,Venezuela,0,Venezuela,2,Venezuela,0,Venezuela,4,Venezuela,"74,50,00,000",Venezuela,"1,00,30,00,00,000",Venezuela,444,Venezuela,"20,07,000",Venezuela,"5,75,000",Venezuela,"3,00,90,00,00,000",Venezuela,"1,42,60,129",Venezuela,"3,16,89,176",Venezuela,"9,12,050",Venezuela,2800,Venezuela,7100,Venezuela,5267
133,Vietnam,0.3559,Vietnam,293,Vietnam,77,Vietnam,0,Vietnam,38,Vietnam,36,Vietnam,138,Vietnam,25,Vietnam,2615,Vietnam,2530,Vietnam,70,Vietnam,1000,Vietnam,85,Vietnam,65,Vietnam,0,Vietnam,6,Vietnam,0,Vietnam,9,Vietnam,"5,50,00,00,000",Vietnam,"96,58,00,00,000",Vietnam,45,Vietnam,"2,71,400",Vietnam,"5,25,000",Vietnam,"4,40,00,00,000",Vietnam,"5,10,43,216",Vietnam,"9,70,40,334",Vietnam,"3,31,210",Vietnam,3444,Vietnam,17702,Vietnam,4616
134,Yemen,1.2412,Yemen,169,Yemen,77,Yemen,0,Yemen,8,Yemen,21,Yemen,61,Yemen,14,Yemen,620,Yemen,615,Yemen,20,Yemen,85,Yemen,150,Yemen,30,Yemen,0,Yemen,0,Yemen,0,Yemen,0,Yemen,"1,40,00,00,000",Yemen,"7,06,80,00,000",Yemen,57,Yemen,12260,Yemen,"1,45,000",Yemen,"3,00,00,00,000",Yemen,"1,12,66,221",Yemen,"2,86,67,230",Yemen,"5,27,968",Yemen,1906,Yemen,0,Yemen,1601
135,Zambia,1.6464,Zambia,108,Zambia,18,Zambia,0,Zambia,11,Zambia,52,Zambia,27,Zambia,0,Zambia,75,Zambia,184,Zambia,0,Zambia,42,Zambia,50,Zambia,0,Zambia,0,Zambia,0,Zambia,0,Zambia,0,Zambia,"4,00,00,000",Zambia,"11,66,00,00,000",Zambia,88,Zambia,0,Zambia,21000,Zambia,0,Zambia,"61,66,905",Zambia,"1,64,45,079",Zambia,"7,52,618",NaN,NaN,Zambia,2250,Zambia,6043
136,Zimbabwe,1.7577,Zimbabwe,90,Zimbabwe,10,Zimbabwe,0,Zimbabwe,14,Zimbabwe,38,Zimbabwe,28,Zimbabwe,6,Zimbabwe,42,Zimbabwe,300,Zimbabwe,0,Zimbabwe,65,Zimbabwe,22,Zimbabwe,0,Zimbabwe,0,Zimbabwe,0,Zimbabwe,0,Zimbabwe,0,Zimbabwe,"10,00,00,000",Zimbabwe,"9,35,70,00,000",Zimbabwe,196,Zimbabwe,0,Zimbabwe,19500,Zimbabwe,0,Zimbabwe,"55,84,086",Zimbabwe,"1,40,30,368",Zimbabwe,"3,90,757",NaN,NaN,Zimbabwe,0,Zimbabwe,3229

In [7]:
df.sample(10)

,Military Strength,Military Strength Power Index,Aircraft Strength,Aircraft Strength value,Fighter/Interceptor Strength,Fighter/Interceptor Strength value,Attack Aircraft Strength,Attack Aircraft Strength value,Transport Aircraft Fleet Strength,Transport Aircraft Fleet Strength value,Trainer Aircraft Fleet,Trainer Aircraft Fleet value,Helicopter Fleet Strength,Helicopter Fleet Strength value,Attack Helicopter Fleet Strength,Attack Helicopter Fleet Strength value,Tank Strength,Tank Strength value,AFV/APC Strength,AFV/APC Strength value,Self-Propelled Artillery Strength,Self-Propelled Artillery Strength value,Towed Artillery Strength,Towed Artillery Strength value,Rocket Projector Strength,Rocket Projector Strength value,Navy Fleet Strengths,Navy Fleet Strengths value,Aircraft Carrier Fleet Strength,Aircraft Carrier Fleet Strength value,Submarine Fleet Strength,Submarine Fleet Strength value,Destroyer Fleet Strength,Destroyer Fleet Strength value,Frigate Fleet Strength,Frigate Fleet Strength value,defense spending budget,defense spending budget value,External Debt,External Debt value,Airport Totals,Airport Totals value,Oil Production,Oil Production value,Oil Consumption,Oil Consumption value,Proven Oil Reserves,Proven Oil Reserves value,Available Manpower,Available Manpower value,Total Population,Total Population value,Total Square Land Area,Total Square Land Area value,Total Coastline Coverage,Total Coastline Coverage value,Total Waterway Coverage,Total Waterway Coverage value,Total Border Coverage,Total Border Coverage value
118,Taiwan,0.4008,Taiwan,744,Taiwan,289,Taiwan,0,Taiwan,19,Taiwan,207,Taiwan,210,Taiwan,91,Taiwan,1180,Taiwan,2000,Taiwan,482,Taiwan,1160,Taiwan,115,Taiwan,117,Taiwan,0,Taiwan,4,Taiwan,4,Taiwan,22,Taiwan,"10,72,50,00,000",Taiwan,"1,81,90,00,00,000",Taiwan,37,Taiwan,196,Taiwan,"10,32,000",Taiwan,"23,80,000",Taiwan,"1,21,96,809",Taiwan,"2,35,45,963",Taiwan,35980,Taiwan,1566,Taiwan,3720,NaN,NaN
105,Slovakia,0.8466,Slovakia,47,Slovakia,10,Slovakia,0,Slovakia,7,Slovakia,8,Slovakia,21,Slovakia,0,Slovakia,20,Slovakia,661,Slovakia,16,Slovakia,9,Slovakia,25,Slovakia,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Slovakia,"2,12,18,17,575",Slovakia,"75,04,00,00,000",Slovakia,35,Slovakia,200,Slovakia,82000,Slovakia,"90,00,000",Slovakia,"27,76,970",Slovakia,"54,45,040",Slovakia,49035,NaN,NaN,Slovakia,172,Slovakia,1587
122,Tunisia,1.4619,Tunisia,147,Tunisia,12,Tunisia,0,Tunisia,14,Tunisia,29,Tunisia,92,Tunisia,0,Tunisia,181,Tunisia,878,Tunisia,20,Tunisia,165,Tunisia,0,Tunisia,50,Tunisia,0,Tunisia,0,Tunisia,0,Tunisia,0,Tunisia,"55,00,00,000",Tunisia,"30,19,00,00,000",Tunisia,29,Tunisia,49170,Tunisia,90500,Tunisia,"42,50,00,000",Tunisia,"58,50,224",Tunisia,"1,15,16,189",Tunisia,"1,63,610",Tunisia,1148,Tunisia,0,Tunisia,1495
23,Chad,1.6383,Chad,35,Chad,0,Chad,6,Chad,6,Chad,4,Chad,17,Chad,3,Chad,60,Chad,372,Chad,10,Chad,51,Chad,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Chad,"20,00,00,000",Chad,"1,72,40,00,000",Chad,59,Chad,"1,28,000",Chad,"1,00,000",Chad,"1,50,00,00,000",Chad,"60,30,834",Chad,"1,58,33,116",Chad,"12,84,000",NaN,NaN,Chad,0,Chad,6406
33,Ecuador,1.0062,Ecuador,108,Ecuador,9,Ecuador,0,Ecuador,22,Ecuador,29,Ecuador,50,Ecuador,0,Ecuador,232,Ecuador,413,Ecuador,15,Ecuador,102,Ecuador,26,Ecuador,19,Ecuador,0,Ecuador,2,Ecuador,0,Ecuador,2,Ecuador,"2,50,00,00,000",Ecuador,"39,29,00,00,000",Ecuador,432,Ecuador,"5,31,300",Ecuador,"2,82,000",Ecuador,"8,27,30,00,000",Ecuador,"76,96,551",Ecuador,"1,64,98,502",Ecuador,"2,83,560",Ecuador,2237,Ecuador,1500,Ecuador,2237
100,Russia,0.0681,Russia,4163,Russia,873,Russia,742,Russia,424,Russia,497,Russia,1522,Russia,531,Russia,12950,Russia,27038,Russia,6083,Russia,4465,Russia,3860,Russia,603,Russia,1,Russia,62,Russia,16,Russia,10,Russia,"48,00,00,00,000",Russia,"5,39,60,00,00,000",Russia,1218,Russia,"1,05,80,000",Russia,"32,25,000",Russia,"80,00,00,00,000",Russia,"6,96,40,160",Russia,"14,21,22,776",Russia,"1,70,98,242",Russia,37653,Russia,"1,02,000",Russia,22408
54,Italy,0.2111,Italy,860,Italy,99,Italy,110,Italy,38,Italy,185,Italy,439,Italy,59,Italy,200,Italy,6947,Italy,54,Italy,108,Italy,21,Italy,249,Italy,2,Italy,8,Italy,4,Italy,12,Italy,"27,80,00,00,000",Italy,"24,44,00,00,00,000",Italy,129,Italy,77530,Italy,"13,00,000",Italy,"55,67,00,000",Italy,"2,80,11,003",Italy,"6,22,46,674",Italy,"3,01,340",Italy,7600,Italy,2400,Italy,1836
107,Somalia,4.6404,Somalia,0,Somalia,0,Somalia,0,Somalia,0,Somalia,0,Somalia,0,Somalia,0,Somalia,10,Somalia,100,Somalia,0,Somalia,30,Somalia,10,Somalia,3,Somalia,0,Somalia,0,Somalia,0,Somalia,0,Somalia,"6,22,00,000",Somalia,"5,30,00,00,000",Somalia,61,Somalia,0,Somalia,6200,Somalia,0,Somalia,"27,02,167",Somalia,"1,12,59,029",Somalia,"6,37,657",Somalia,3025,Somalia,0,Somalia,2385
131,Uzbekistan,0.8086,Uzbekistan,185,Uzbekistan,66,Uzbekistan,20,Uzbekistan,18,Uzbekistan,2,Uzbekistan,79,Uzbekistan,25,Uzbekistan,420,Uzbekistan,1215,Uzbekistan,137,Uzbekistan,0,Uzbekistan,98,Uzbekistan,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Uzbekistan,"97,50,00,000",Uzbekistan,"16,90,00,00,000",Uzbekistan,53,Uzbekistan,46070,Uzbekistan,"1,42,000",Uzbekistan,"59,40,00,000",Uzbekistan,"1,59,12,566",Uzbekistan,"3,00,23,709",Uzbekistan,"4,47,400",Uzbekistan,420,Uzbekistan,1100,Uzbekistan,6893
46,Honduras,2.0943,Honduras,46,Honduras,3,Honduras,9,Honduras,11,Honduras,10,Honduras,12,Honduras,0,Honduras,19,Honduras,92,Honduras,0,Honduras,176,Honduras,0,Honduras,59,Honduras,0,Honduras,0,Honduras,0,Honduras,0,Honduras,"20,50,00,000",Honduras,"8,62,50,00,000",Honduras,103,Honduras,0,Honduras,60000,Honduras,0,Honduras,"41,04,696",Honduras,"91,82,766",Honduras,"1,12,090",Honduras,832,Honduras,465,Honduras,1575

In [8]:
df.shape

(137, 60)

In [9]:
df.describe()

,Military Strength,Military Strength Power Index,Aircraft Strength,Aircraft Strength value,Fighter/Interceptor Strength,Fighter/Interceptor Strength value,Attack Aircraft Strength,Attack Aircraft Strength value,Transport Aircraft Fleet Strength,Transport Aircraft Fleet Strength value,Trainer Aircraft Fleet,Trainer Aircraft Fleet value,Helicopter Fleet Strength,Helicopter Fleet Strength value,Attack Helicopter Fleet Strength,Attack Helicopter Fleet Strength value,Tank Strength,Tank Strength value,AFV/APC Strength,AFV/APC Strength value,Self-Propelled Artillery Strength,Self-Propelled Artillery Strength value,Towed Artillery Strength,Towed Artillery Strength value,Rocket Projector Strength,Rocket Projector Strength value,Navy Fleet Strengths,Navy Fleet Strengths value,Aircraft Carrier Fleet Strength,Aircraft Carrier Fleet Strength value,Submarine Fleet Strength,Submarine Fleet Strength value,Destroyer Fleet Strength,Destroyer Fleet Strength value,Frigate Fleet Strength,Frigate Fleet Strength value,defense spending budget,defense spending budget value,External Debt,External Debt value,Airport Totals,Airport Totals value,Oil Production,Oil Production value,Oil Consumption,Oil Consumption value,Proven Oil Reserves,Proven Oil Reserves value,Available Manpower,Available Manpower value,Total Population,Total Population value,Total Square Land Area,Total Square Land Area value,Total Coastline Coverage,Total Coastline Coverage value,Total Waterway Coverage,Total Waterway Coverage value,Total Border Coverage,Total Border Coverage value
count,137,137.0000,137,137,137,137,137,137,137,137,137,137,137,137,137,137,137,137,137,137,137,137,137,137,137,137,123,123,114,114,114,114,114,114,114,114,137,137,137,137,137,137,137,137,137,137,137,137,137,137,137,137,137,137,108,108,137,137,128,128
unique,137,137.0000,137,113,137,63,137,38,137,49,137,77,137,96,137,45,137,106,137,129,137,70,137,91,137,68,123,78,114,5,114,20,114,11,114,18,137,124,137,137,137,108,137,88,137,102,137,84,137,137,137,137,137,137,108,103,137,92,128,124
top,Albania,2.3137,Albania,19,Albania,0,Albania,0,Albania,0,Albania,0,Albania,8,Albania,0,Albania,0,Albania,2000,Albania,0,Albania,0,Albania,0,Albania,0,Albania,0,Albania,0,Albania,0,Albania,0,Albania,"2,50,00,00,000",Albania,"9,50,50,00,000",Albania,18,Albania,0,Albania,18500,Albania,0,Albania,"15,19,438",Albania,"30,57,220",Albania,28748,Albania,400,Albania,0,Albania,2237
freq,1,1.0000,1,5,1,45,1,75,1,15,1,24,1,4,1,62,1,23,1,4,1,51,1,24,1,46,1,13,1,101,1,73,1,102,1,60,1,3,1,1,1,3,1,45,1,4,1,45,1,1,1,1,1,1,1,2,1,38,1,2

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 137 entries, 0 to 136
Data columns (total 60 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   Military Strength                        137 non-null    object
 1   Military Strength Power Index            137 non-null    object
 2   Aircraft Strength                        137 non-null    object
 3   Aircraft Strength value                  137 non-null    object
 4   Fighter/Interceptor Strength             137 non-null    object
 5   Fighter/Interceptor Strength value       137 non-null    object
 6   Attack Aircraft Strength                 137 non-null    object
 7   Attack Aircraft Strength value           137 non-null    object
 8   Transport Aircraft Fleet Strength        137 non-null    object
 9   Transport Aircraft Fleet Strength value  137 non-null    object
 10  Trainer Aircraft Fleet                   137 non-null    object
 11  Trainer Aircraft Fleet value             137 non-null    object
 12  Helicopter Fleet Strength                137 non-null    object
 13  Helicopter Fleet Strength value          137 non-null    object
 14  Attack Helicopter Fleet Strength         137 non-null    object
 15  Attack Helicopter Fleet Strength value   137 non-null    object
 16  Tank Strength                            137 non-null    object
 17  Tank Strength value                      137 non-null    object
 18  AFV/APC Strength                         137 non-null    object
 19  AFV/APC Strength value                   137 non-null    object
 20  Self-Propelled Artillery Strength        137 non-null    object
 21  Self-Propelled Artillery Strength value  137 non-null    object
 22  Towed Artillery Strength                 137 non-null    object
 23  Towed Artillery Strength value           137 non-null    object
 24  Rocket Projector Strength                137 non-null    object
 25  Rocket Projector Strength value          137 non-null    object
 26  Navy Fleet Strengths                     123 non-null    object
 27  Navy Fleet Strengths value               123 non-null    object
 28  Aircraft Carrier Fleet Strength          114 non-null    object
 29  Aircraft Carrier Fleet Strength value    114 non-null    object
 30  Submarine Fleet Strength                 114 non-null    object
 31  Submarine Fleet Strength value           114 non-null    object
 32  Destroyer Fleet Strength                 114 non-null    object
 33  Destroyer Fleet Strength value           114 non-null    object
 34  Frigate Fleet Strength                   114 non-null    object
 35  Frigate Fleet Strength value             114 non-null    object
 36  defense spending budget                  137 non-null    object
 37  defense spending budget value            137 non-null    object
 38  External Debt                            137 non-null    object
 39  External Debt value                      137 non-null    object
 40  Airport Totals                           137 non-null    object
 41  Airport Totals value                     137 non-null    object
 42  Oil Production                           137 non-null    object
 43  Oil Production value                     137 non-null    object
 44  Oil Consumption                          137 non-null    object
 45  Oil Consumption value                    137 non-null    object
 46  Proven Oil Reserves                      137 non-null    object
 47  Proven Oil Reserves value                137 non-null    object
 48  Available Manpower                       137 non-null    object
 49  Available Manpower value                 137 non-null    object
 50  Total Population                         137 non-null    object
 51  Total Population value                   137 non-null    object
 52  Total Square Land Area                   137 non-null    object
 53  Total Square Land Area value             137 non-null    object
 54  Total Coastline Coverage                 108 non-null    object
 55  Total Coastline Coverage value           108 non-null    object
 56  Total Waterway Coverage                  137 non-null    object
 57  Total Waterway Coverage value            137 non-null    object
 58  Total Border Coverage                    128 non-null    object
 59  Total Border Coverage value              128 non-null    object
dtypes: object(60)
memory usage: 64.3+ KB

In [11]:
df.isnull().sum()

0
Military Strength                           0
Military Strength Power Index               0
Aircraft Strength                           0
Aircraft Strength value                     0
Fighter/Interceptor Strength                0
Fighter/Interceptor Strength value          0
Attack Aircraft Strength                    0
Attack Aircraft Strength value              0
Transport Aircraft Fleet Strength           0
Transport Aircraft Fleet Strength value     0
Trainer Aircraft Fleet                      0
Trainer Aircraft Fleet value                0
Helicopter Fleet Strength                   0
Helicopter Fleet Strength value             0
Attack Helicopter Fleet Strength            0
Attack Helicopter Fleet Strength value      0
Tank Strength                               0
Tank Strength value                         0
AFV/APC Strength                            0
AFV/APC Strength value                      0
Self-Propelled Artillery Strength           0
Self-Propelled Artillery Strength value     0
Towed Artillery Strength                    0
Towed Artillery Strength value              0
Rocket Projector Strength                   0
Rocket Projector Strength value             0
Navy Fleet Strengths                       14
Navy Fleet Strengths value                 14
Aircraft Carrier Fleet Strength            23
Aircraft Carrier Fleet Strength value      23
Submarine Fleet Strength                   23
Submarine Fleet Strength value             23
Destroyer Fleet Strength                   23
Destroyer Fleet Strength value             23
Frigate Fleet Strength                     23
Frigate Fleet Strength value               23
defense spending budget                     0
defense spending budget value               0
External Debt                               0
External Debt value                         0
Airport Totals                              0
Airport Totals value                        0
Oil Production                              0
Oil Production value                        0
Oil Consumption                             0
Oil Consumption value                       0
Proven Oil Reserves                         0
Proven Oil Reserves value                   0
Available Manpower                          0
Available Manpower value                    0
Total Population                            0
Total Population value                      0
Total Square Land Area                      0
Total Square Land Area value                0
Total Coastline Coverage                   29
Total Coastline Coverage value             29
Total Waterway Coverage                     0
Total Waterway Coverage value               0
Total Border Coverage                       9
Total Border Coverage value                 9
dtype: int64

In [12]:
### sütunlarda tekrar eden ülke isimleri var bu sütunları kaldıracağız.

In [13]:
df_country = df.iloc[:, 0]        # İlk ülke adını al
df_values = df.iloc[:, 1::2]      # Tek indeksli sayısal sütunları al

df = pd.concat([df_country, df_values], axis=1)

In [14]:
df.head()

,Military Strength,Military Strength Power Index,Aircraft Strength value,Fighter/Interceptor Strength value,Attack Aircraft Strength value,Transport Aircraft Fleet Strength value,Trainer Aircraft Fleet value,Helicopter Fleet Strength value,Attack Helicopter Fleet Strength value,Tank Strength value,AFV/APC Strength value,Self-Propelled Artillery Strength value,Towed Artillery Strength value,Rocket Projector Strength value,Navy Fleet Strengths value,Aircraft Carrier Fleet Strength value,Submarine Fleet Strength value,Destroyer Fleet Strength value,Frigate Fleet Strength value,defense spending budget value,External Debt value,Airport Totals value,Oil Production value,Oil Consumption value,Proven Oil Reserves value,Available Manpower value,Total Population value,Total Square Land Area value,Total Coastline Coverage value,Total Waterway Coverage value,Total Border Coverage value
0,Albania,2.3137,19,0,0,0,0,19,0,0,467,0,0,0,38,0,0,0,0,"25,00,00,000","9,50,50,00,000",4,16000,42500,"16,83,00,000","15,19,438","30,57,220",28748,362,41,691
1,Algeria,0.4659,551,103,22,59,87,257,45,880,7361,320,240,316,201,0,6,0,5,"13,00,00,00,000","6,26,00,00,000",157,"13,06,000","3,25,000","12,20,00,00,000","2,07,41,263","4,16,57,488","23,81,741",998,0,6734
2,Angola,0.8379,295,72,18,30,47,126,15,379,595,28,357,115,57,0,0,0,0,"7,00,00,00,000","42,08,00,00,000",176,"16,66,000",82300,"8,27,30,00,000","62,44,205","3,03,55,880","12,46,700",1600,1300,5369
3,Argentina,0.6521,227,24,7,9,64,100,0,370,739,83,172,26,49,0,2,4,0,"4,20,00,00,000","2,14,90,00,00,000",1138,"4,79,400","6,85,000","2,18,50,00,000","2,01,79,430","4,46,94,198","27,80,400",4989,11000,11968
4,Armenia,2.1251,64,0,9,3,13,37,20,110,748,38,150,68,0,NaN,NaN,NaN,NaN,"1,38,50,00,000","10,41,00,00,000",11,0,47500,0,"16,96,085","30,38,217",29743,NaN,0,1570

In [15]:
df.shape

(137, 31)

In [17]:
df.isnull().sum().sum()

np.int64(144)

In [16]:
# Boş değerler doğrudan bir ülkeyle ilgili bilgi verdiği için veri oldurma yöntemleri yanlış bir yaklaşım olacağını düşünüyorum
# o yüzden nan değerleri 0 olarak düzelteceğim.

In [18]:
df = df.fillna(0)

In [19]:
df.isnull().sum().sum()

np.int64(0)

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 137 entries, 0 to 136
Data columns (total 31 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   Military Strength                        137 non-null    object
 1   Military Strength Power Index            137 non-null    float64
 2   Aircraft Strength value                  137 non-null    int64
 3   Fighter/Interceptor Strength value       137 non-null    int64
 4   Attack Aircraft Strength value           137 non-null    int64
 5   Transport Aircraft Fleet Strength value  137 non-null    int64
 6   Trainer Aircraft Fleet value             137 non-null    int64
 7   Helicopter Fleet Strength value          137 non-null    int64
 8   Attack Helicopter Fleet Strength value   137 non-null    int64
 9   Tank Strength value                      137 non-null    int64
 10  AFV/APC Strength value                   137 non-null    int64
 11  Self-Propelled Artillery Strength value  137 non-null    int64
 12  Towed Artillery Strength value           137 non-null    int64
 13  Rocket Projector Strength value          137 non-null    int64
 14  Navy Fleet Strengths value               137 non-null    int64
 15  Aircraft Carrier Fleet Strength value    137 non-null    int64
 16  Submarine Fleet Strength value           137 non-null    int64
 17  Destroyer Fleet Strength value           137 non-null    int64
 18  Frigate Fleet Strength value             137 non-null    int64
 19  defense spending budget value            137 non-null    object
 20  External Debt value                      137 non-null    object
 21  Airport Totals value                     137 non-null    int64
 22  Oil Production value                     137 non-null    object
 23  Oil Consumption value                    137 non-null    object
 24  Proven Oil Reserves value                137 non-null    object
 25  Available Manpower value                 137 non-null    object
 26  Total Population value                   137 non-null    object
 27  Total Square Land Area value             137 non-null    object
 28  Total Coastline Coverage value           137 non-null    object
 29  Total Waterway Coverage value            137 non-null    object
 30  Total Border Coverage value              137 non-null    int64
dtypes: float64(1), int64(19), object(11)
memory usage: 33.3+ KB

In [22]:
df.sample(10)

,Military Strength,Military Strength Power Index,Aircraft Strength value,Fighter/Interceptor Strength value,Attack Aircraft Strength value,Transport Aircraft Fleet Strength value,Trainer Aircraft Fleet value,Helicopter Fleet Strength value,Attack Helicopter Fleet Strength value,Tank Strength value,AFV/APC Strength value,Self-Propelled Artillery Strength value,Towed Artillery Strength value,Rocket Projector Strength value,Navy Fleet Strengths value,Aircraft Carrier Fleet Strength value,Submarine Fleet Strength value,Destroyer Fleet Strength value,Frigate Fleet Strength value,defense spending budget value,External Debt value,Airport Totals value,Oil Production value,Oil Consumption value,Proven Oil Reserves value,Available Manpower value,Total Population value,Total Square Land Area value,Total Coastline Coverage value,Total Waterway Coverage value,Total Border Coverage value
37,Ethiopia,0.8581,86,24,0,9,20,33,8,400,114,67,650,183,0,0,0,0,0,"35,00,00,000","26,05,00,00,000",57,0,55000,"4,28,000","4,11,43,474","10,83,86,391","11,04,300",0,"1,04,300",5925
55,Ivory Coast,2.0236,8,0,0,4,0,4,3,15,109,0,7,6,10,0,0,0,0,"55,00,00,000","13,07,00,00,000",27,54000,25600,"10,00,00,000","1,11,60,747","2,62,60,582","3,22,463",515,980,3458
14,Bosnia and Herzegovina,3.8586,19,0,0,0,0,19,0,320,332,24,837,143,0,0,0,0,0,"16,50,00,000","10,87,00,00,000",24,0,32500,0,"23,94,632","38,49,891",51197,20,0,1543
91,Panama,3.6537,39,0,0,11,4,23,0,0,65,0,0,0,20,0,0,0,0,"50,00,00,000","91,53,00,00,000",117,0,"1,00,000",0,"17,59,698","38,00,644",75420,2490,800,687
132,Venezuela,0.6449,260,38,0,52,82,86,10,390,600,73,104,36,49,0,2,0,4,"74,50,00,000","1,00,30,00,00,000",444,"20,07,000","5,75,000","3,00,90,00,00,000","1,42,60,129","3,16,89,176","9,12,050",2800,7100,5267
113,Sudan,1.3017,190,46,38,22,11,73,43,690,400,10,0,0,18,0,0,0,0,"2,47,00,00,000","56,05,00,00,000",74,"1,02,300",96800,"5,00,00,00,000","2,40,61,430","4,31,20,843","18,61,484",853,1723,6819
33,Ecuador,1.0062,108,9,0,22,29,50,0,232,413,15,102,26,19,0,2,0,2,"2,50,00,00,000","39,29,00,00,000",432,"5,31,300","2,82,000","8,27,30,00,000","76,96,551","1,64,98,502","2,83,560",2237,1500,2237
102,Serbia,0.9479,109,9,17,1,38,44,0,293,904,87,144,88,19,0,0,0,0,"90,70,00,000","29,50,00,00,000",26,18740,75000,"7,75,00,000","34,68,274","70,78,110",77474,0,587,2322
82,New Zealand,1.3684,48,0,0,7,13,22,0,0,200,0,24,0,11,0,0,0,2,"4,30,00,00,000","91,62,00,00,000",123,31480,"1,50,000","5,69,00,000","21,15,989","45,45,627","2,67,710",15134,0,0
76,Morocco,0.8408,214,46,0,31,67,64,0,1443,2901,505,200,144,121,0,0,0,3,"10,00,00,00,000","51,48,00,00,000",55,160,"2,06,000","6,84,000","1,71,57,065","3,43,14,130","4,46,550",1835,0,2363

In [24]:
# tüm sütunları int yapmak için
# virgülle ayrılmış sayılar olduğu için önce string yapıp virgülleri kaldırdık. sonra int 
for col in df.columns[2:]:
    df[col] = df[col].astype(str).str.replace(",", "").astype(int)

In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 137 entries, 0 to 136
Data columns (total 31 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   Military Strength                        137 non-null    object
 1   Military Strength Power Index            137 non-null    float64
 2   Aircraft Strength value                  137 non-null    int64
 3   Fighter/Interceptor Strength value       137 non-null    int64
 4   Attack Aircraft Strength value           137 non-null    int64
 5   Transport Aircraft Fleet Strength value  137 non-null    int64
 6   Trainer Aircraft Fleet value             137 non-null    int64
 7   Helicopter Fleet Strength value          137 non-null    int64
 8   Attack Helicopter Fleet Strength value   137 non-null    int64
 9   Tank Strength value                      137 non-null    int64
 10  AFV/APC Strength value                   137 non-null    int64
 11  Self-Propelled Artillery Strength value  137 non-null    int64
 12  Towed Artillery Strength value           137 non-null    int64
 13  Rocket Projector Strength value          137 non-null    int64
 14  Navy Fleet Strengths value               137 non-null    int64
 15  Aircraft Carrier Fleet Strength value    137 non-null    int64
 16  Submarine Fleet Strength value           137 non-null    int64
 17  Destroyer Fleet Strength value           137 non-null    int64
 18  Frigate Fleet Strength value             137 non-null    int64
 19  defense spending budget value            137 non-null    int64
 20  External Debt value                      137 non-null    int64
 21  Airport Totals value                     137 non-null    int64
 22  Oil Production value                     137 non-null    int64
 23  Oil Consumption value                    137 non-null    int64
 24  Proven Oil Reserves value                137 non-null    int64
 25  Available Manpower value                 137 non-null    int64
 26  Total Population value                   137 non-null    int64
 27  Total Square Land Area value             137 non-null    int64
 28  Total Coastline Coverage value           137 non-null    int64
 29  Total Waterway Coverage value            137 non-null    int64
 30  Total Border Coverage value              137 non-null    int64
dtypes: float64(1), int64(29), object(1)
memory usage: 33.3+ KB