In [1]:
import pandas as pd

In [2]:
ls

 Volume in drive C has no label.
 Volume Serial Number is EA81-4F3B

 Directory of C:\Users\USER\Desktop\Artificial_Intelligence_Course\week3_homework\ Loan Prediction - Classification

06.08.2025  22:25            55.226  Loan Prediction - Classification.ipynb
06.08.2025  22:25    <DIR>          .
06.08.2025  19:50    <DIR>          ..
06.08.2025  19:50    <DIR>          .ipynb_checkpoints
06.08.2025  19:50        16.542.823 LoanPrediction.zip
06.08.2025  19:50           130.260 LoansTraining data dictionary.docx
06.08.2025  19:50        47.630.611 LoansTrainingSet.csv
               4 File(s)     64.358.920 bytes
               3 Dir(s)  153.073.319.936 bytes free

In [3]:
df = pd.read_csv('LoansTrainingSet.csv')

C:\Users\USER\AppData\Local\Temp\ipykernel_16504\3228652955.py:1: DtypeWarning: Columns (16) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('LoansTrainingSet.csv')

In [4]:
df.head()

,Loan ID,Customer ID,Loan Status,Current Loan Amount,Term,Credit Score,Years in current job,Home Ownership,Annual Income,Purpose,Monthly Debt,Years of Credit History,Months since last delinquent,Number of Open Accounts,Number of Credit Problems,Current Credit Balance,Maximum Open Credit,Bankruptcies,Tax Liens
0,000025bb-5694-4cff-b17d-192b1a98ba44,5ebc8bb1-5eb9-4404-b11b-a6eebc401a19,Fully Paid,11520,Short Term,741.0,10+ years,Home Mortgage,33694.0,Debt Consolidation,$584.03,12.3,41.0,10,0,6760,16056,0.0,0.0
1,00002c49-3a29-4bd4-8f67-c8f8fbc1048c,927b388d-2e01-423f-a8dc-f7e42d668f46,Fully Paid,3441,Short Term,734.0,4 years,Home Mortgage,42269.0,other,"$1,106.04",26.3,NaN,17,0,6262,19149,0.0,0.0
2,00002d89-27f3-409b-aa76-90834f359a65,defce609-c631-447d-aad6-1270615e89c4,Fully Paid,21029,Short Term,747.0,10+ years,Home Mortgage,90126.0,Debt Consolidation,"$1,321.85",28.8,NaN,5,0,20967,28335,0.0,0.0
3,00005222-b4d8-45a4-ad8c-186057e24233,070bcecb-aae7-4485-a26a-e0403e7bb6c5,Fully Paid,18743,Short Term,747.0,10+ years,Own Home,38072.0,Debt Consolidation,$751.92,26.2,NaN,9,0,22529,43915,0.0,0.0
4,0000757f-a121-41ed-b17b-162e76647c1f,dde79588-12f0-4811-bab0-e2b07f633fcd,Fully Paid,11731,Short Term,746.0,4 years,Rent,50025.0,Debt Consolidation,$355.18,11.5,NaN,12,0,17391,37081,0.0,0.0

In [5]:
df.shape

(256984, 19)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 256984 entries, 0 to 256983
Data columns (total 19 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   Loan ID                       256984 non-null  object
 1   Customer ID                   256984 non-null  object
 2   Loan Status                   256984 non-null  object
 3   Current Loan Amount           256984 non-null  int64
 4   Term                          256984 non-null  object
 5   Credit Score                  195308 non-null  float64
 6   Years in current job          245508 non-null  object
 7   Home Ownership                256984 non-null  object
 8   Annual Income                 195308 non-null  float64
 9   Purpose                       256984 non-null  object
 10  Monthly Debt                  256984 non-null  object
 11  Years of Credit History       256984 non-null  float64
 12  Months since last delinquent  116601 non-null  float64
 13  Number of Open Accounts       256984 non-null  int64
 14  Number of Credit Problems     256984 non-null  int64
 15  Current Credit Balance        256984 non-null  int64
 16  Maximum Open Credit           256984 non-null  object
 17  Bankruptcies                  256455 non-null  float64
 18  Tax Liens                     256961 non-null  float64
dtypes: float64(6), int64(4), object(9)
memory usage: 37.3+ MB

In [7]:
df.describe()

,Current Loan Amount,Credit Score,Annual Income,Years of Credit History,Months since last delinquent,Number of Open Accounts,Number of Credit Problems,Current Credit Balance,Bankruptcies,Tax Liens
count,2.569840e+05,195308.000000,1.953080e+05,256984.000000,116601.000000,256984.000000,256984.000000,2.569840e+05,256455.000000,256961.000000
mean,1.371331e+07,1251.116099,7.195272e+04,18.290195,34.881450,11.106267,0.156628,1.540656e+04,0.110316,0.027203
std,3.438131e+07,1762.016848,5.887757e+04,7.075747,21.854165,4.982982,0.460731,1.966506e+04,0.336229,0.245950
min,5.050000e+02,585.000000,0.000000e+00,3.400000,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000
25%,8.299000e+03,714.000000,4.432100e+04,13.500000,16.000000,8.000000,0.000000,5.974000e+03,0.000000,0.000000
50%,1.429800e+04,733.000000,6.124200e+04,17.000000,32.000000,10.000000,0.000000,1.107800e+04,0.000000,0.000000
75%,2.436700e+04,744.000000,8.646200e+04,21.700000,51.000000,14.000000,0.000000,1.931900e+04,0.000000,0.000000
max,1.000000e+08,7510.000000,8.713547e+06,70.500000,176.000000,76.000000,11.000000,1.731412e+06,7.000000,11.000000

In [8]:
df = df.drop(df[['Loan ID','Customer ID']], axis = 1)

In [9]:
df.head()

,Loan Status,Current Loan Amount,Term,Credit Score,Years in current job,Home Ownership,Annual Income,Purpose,Monthly Debt,Years of Credit History,Months since last delinquent,Number of Open Accounts,Number of Credit Problems,Current Credit Balance,Maximum Open Credit,Bankruptcies,Tax Liens
0,Fully Paid,11520,Short Term,741.0,10+ years,Home Mortgage,33694.0,Debt Consolidation,$584.03,12.3,41.0,10,0,6760,16056,0.0,0.0
1,Fully Paid,3441,Short Term,734.0,4 years,Home Mortgage,42269.0,other,"$1,106.04",26.3,NaN,17,0,6262,19149,0.0,0.0
2,Fully Paid,21029,Short Term,747.0,10+ years,Home Mortgage,90126.0,Debt Consolidation,"$1,321.85",28.8,NaN,5,0,20967,28335,0.0,0.0
3,Fully Paid,18743,Short Term,747.0,10+ years,Own Home,38072.0,Debt Consolidation,$751.92,26.2,NaN,9,0,22529,43915,0.0,0.0
4,Fully Paid,11731,Short Term,746.0,4 years,Rent,50025.0,Debt Consolidation,$355.18,11.5,NaN,12,0,17391,37081,0.0,0.0

In [10]:
df.shape

(256984, 17)

## Boş verileri işleme

In [11]:
df.isnull().sum()

Loan Status                          0
Current Loan Amount                  0
Term                                 0
Credit Score                     61676
Years in current job             11476
Home Ownership                       0
Annual Income                    61676
Purpose                              0
Monthly Debt                         0
Years of Credit History              0
Months since last delinquent    140383
Number of Open Accounts              0
Number of Credit Problems            0
Current Credit Balance               0
Maximum Open Credit                  0
Bankruptcies                       529
Tax Liens                           23
dtype: int64

In [12]:
def mis_val_cal(df) :
    mis_val = df.isnull().sum() 
    mis_val_percent = 100 * df.isnull().sum() / len(df) # eksik verilerin yüzde kaç olduğunu bulduk
    mis_val_table = pd.concat([mis_val, mis_val_percent], axis=1) # eksik verilerin sayısıyla yüzdesini birleştirdik
    mis_val_table_ren_columns = mis_val_table.rename(
        columns = {0 : 'Missing Values', 1 : '% of Total Values'}) # kolon ismi verdik
    return mis_val_table_ren_columns

In [13]:
mis_val_cal(df)

                              Missing Values  % of Total Values
Loan Status                                0           0.000000
Current Loan Amount                        0           0.000000
Term                                       0           0.000000
Credit Score                           61676          23.999938
Years in current job                   11476           4.465648
Home Ownership                             0           0.000000
Annual Income                          61676          23.999938
Purpose                                    0           0.000000
Monthly Debt                               0           0.000000
Years of Credit History                    0           0.000000
Months since last delinquent          140383          54.627136
Number of Open Accounts                    0           0.000000
Number of Credit Problems                  0           0.000000
Current Credit Balance                     0           0.000000
Maximum Open Credit                        0           0.000000
Bankruptcies                             529           0.205849
Tax Liens                                 23           0.008950

In [14]:
df = df.drop(df[['Months since last delinquent']] , axis = 1) # kolonun yüzde 50 den fazlası boş olduğu için kolonu kaldırdık

In [15]:
df.shape

(256984, 16)

In [16]:
df.dropna(subset=["Years in current job"], inplace=True) # Years in current job sütunundaki nan olan satırları sildik

In [17]:
df.shape

(245508, 16)

In [18]:
df.dropna(subset=["Bankruptcies"], inplace=True)

In [19]:
df.dropna(subset=["Tax Liens"], inplace=True)

In [20]:
mis_val_cal(df)

                           Missing Values  % of Total Values
Loan Status                             0           0.000000
Current Loan Amount                     0           0.000000
Term                                    0           0.000000
Credit Score                        58880          24.034713
Years in current job                    0           0.000000
Home Ownership                          0           0.000000
Annual Income                       58880          24.034713
Purpose                                 0           0.000000
Monthly Debt                            0           0.000000
Years of Credit History                 0           0.000000
Number of Open Accounts                 0           0.000000
Number of Credit Problems               0           0.000000
Current Credit Balance                  0           0.000000
Maximum Open Credit                     0           0.000000
Bankruptcies                            0           0.000000
Tax Liens                               0           0.000000

In [31]:
df['Credit Score'] = df['Credit Score'].fillna(df['Credit Score'].mean()) # kredi skoru ortalama ile dolduruldu

KeyError: ('Credit Score', 'Annual Income')

                           Missing Values  % of Total Values
Loan Status                             0           0.000000
Current Loan Amount                     0           0.000000
Term                                    0           0.000000
Credit Score                            0           0.000000
Years in current job                    0           0.000000
Home Ownership                          0           0.000000
Annual Income                       58880          24.034713
Purpose                                 0           0.000000
Monthly Debt                            0           0.000000
Years of Credit History                 0           0.000000
Number of Open Accounts                 0           0.000000
Number of Credit Problems               0           0.000000
Current Credit Balance                  0           0.000000
Maximum Open Credit                     0           0.000000
Bankruptcies                            0           0.000000
Tax Liens                               0           0.000000